package com.shapeshed.aerial.ui.theme

import androidx.compose.ui.graphics.Color

val primaryLight = Color(0xFF006874)
val onPrimaryLight = Color(0xFFFFFFFF)
val primaryContainerLight = Color(0xFF9EEFFD)
val onPrimaryContainerLight = Color(0xFF001F24)
val secondaryLight = Color(0xFF4A6267)
val onSecondaryLight = Color(0xFFFFFFFF)
val secondaryContainerLight = Color(0xFFCCE7ED)
val onSecondaryContainerLight = Color(0xFF051F23)
val tertiaryLight = Color(0xFF525E7D)
val onTertiaryLight = Color(0xFFFFFFFF)
val tertiaryContainerLight = Color(0xFFD9E2FF)
val onTertiaryContainerLight = Color(0xFF0E1B36)
val errorLight = Color(0xFFBA1A1A)
val onErrorLight = Color(0xFFFFFFFF)
val errorContainerLight = Color(0xFFFFDAD6)
val onErrorContainerLight = Color(0xFF410002)
val backgroundLight = Color(0xFFF5FAFB)
val onBackgroundLight = Color(0xFF171D1E)
val surfaceLight = Color(0xFFF5FAFB)
val onSurfaceLight = Color(0xFF171D1E)
val surfaceVariantLight = Color(0xFFDBE4E6)
val onSurfaceVariantLight = Color(0xFF3F484A)
val outlineLight = Color(0xFF6F797A)

val primaryDark = Color(0xFF82D3E0)
val onPrimaryDark = Color(0xFF00363D)
val primaryContainerDark = Color(0xFF004F58)
val onPrimaryContainerDark = Color(0xFF9EEFFD)
val secondaryDark = Color(0xFFB1CBD1)
val onSecondaryDark = Color(0xFF1C3438)
val secondaryContainerDark = Color(0xFF324B4F)
val onSecondaryContainerDark = Color(0xFFCCE7ED)
val tertiaryDark = Color(0xFFBAC6EA)
val onTertiaryDark = Color(0xFF24304C)
val tertiaryContainerDark = Color(0xFF3B4664)
val onTertiaryContainerDark = Color(0xFFD9E2FF)
val errorDark = Color(0xFFFFB4AB)
val onErrorDark = Color(0xFF690005)
val errorContainerDark = Color(0xFF93000A)
val onErrorContainerDark = Color(0xFFFFDAD6)
val backgroundDark = Color(0xFF0E1415)
val onBackgroundDark = Color(0xFFDDE3E5)
val surfaceDark = Color(0xFF0E1415)
val onSurfaceDark = Color(0xFFDDE3E5)
val surfaceVariantDark = Color(0xFF3F484A)
val onSurfaceVariantDark = Color(0xFFBFC8CA)
val outlineDark = Color(0xFF899294)
